apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: waves-demo
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/Ashutoshdocs//argocd-syncwaves-demo.git
    targetRevision: HEAD
    path: Chapter13_Miscellaneous/argocd-propagation-demo/argocd/manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: waves-demo
  # Manual sync on purpose, so you choose when each sync starts and can watch it.
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
