apiVersion: v1
kind: Service
metadata:
  name: alice-web-svc
  labels:
    app: alice-web
    owner: alice
spec:
  type: NodePort
  selector:
    app: alice-web
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 31001
