apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-orphan
  namespace: argocd
  finalizers:
    # Deleting this Application also deletes its resources (cascade).
    # Use ".../background" instead for background cascade deletion.
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/Ashutoshdocs/argocd-propagation-demo.git
    targetRevision: HEAD
    path: Chapter13_Miscellaneous/argocd-propagation-demo/argocd/manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: demo-orphan
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      # How Argo CD deletes resources it PRUNES (foreground | background | orphan)
      - PrunePropagationPolicy=orphan
