apiVersion: v1
kind: Service
metadata:
  name: web
  labels: { app: web, env: qa }
spec:
  type: NodePort
  selector: { app: web, env: qa }
  ports:
    - { name: http, port: 80, targetPort: 80, nodePort: 30082 }   # http://<node-ip>:30082
