apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: stable-canary-demo
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Ashutoshdocs/lectureArgoCD.git
    targetRevision: main
    path: deploymentstratergies/stable-canary/manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: stable-canary
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
