apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cli-nginx-demo
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io

spec:
  project: default

  source:
    repoURL: https://github.com/Ashutoshdocs/lectureArgoCD.git
    targetRevision: HEAD
    path: Chapter02_Ways_to_deploy/Chapter02_argoCD_CLI_based/manifests

  destination:
    server: https://kubernetes.default.svc
    namespace: cli-nginx-demo

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true
