# BLUE = the current/live version (v1). Runs at all times.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bluegreen-blue
  namespace: blue-green
  labels:
    app: bluegreen-demo
    color: blue
spec:
  replicas: 3
  selector:
    matchLabels:
      app: bluegreen-demo
      color: blue
  template:
    metadata:
      labels:
        app: bluegreen-demo
        color: blue
    spec:
      containers:
        - name: hello
          image: gcr.io/google-samples/hello-app:1.0   # v1
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 2
            periodSeconds: 3
